apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-inspector-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code-inspector-api
  template:
    metadata:
      labels:
        app: code-inspector-api
    spec:
      containers:
        - name: api
          image: example/api:latest
          env:
            - name: DATABASE_PASSWORD
              value: "prod-password"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: code-inspector-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: code-inspector-api
